directories:
  output: release
  buildResources: build
appId: com.leyutune.producer
productName: LeyuTune Producer
copyright: Copyright © 2026
files:
  - filter:
      - out/**/*
      - package.json
      - prisma/**/*
      - generated/prisma/**/*
      - node_modules/prisma/**/*
      - node_modules/adm-zip/**/*
asarUnpack:
  - generated/prisma/**
  - node_modules/prisma/**
  - prisma/**
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 42.3.3
